name: "[Test] misc"

on:
  schedule:
    # Runs at midnight UTC every day at 01:00 AM CET
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - ".github/workflows/test-misc.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  urls-health:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn workspace @trezor/urls test:e2e

  translations-unused:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn workspace @trezor/suite translations:list-unused

  media-duplicates:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    strategy:
      fail-fast: false
      matrix:
        extension: [".png", ".jpg", ".mp4", ".webm", ".svg"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ./scripts/ci/find_duplicates.sh ./packages/suite-data/files ${{ matrix.extension }}

  test-unit:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn message-system-sign-config
      - run: yarn test:unit

  utility-scripts:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn generate-package @trezor/meow-package
      - run: rm -rf packages/meow-package
